/**
 * @module EditDiffCollector
 * @description CREDEAL v3 IM Edit Diff Collector
 * 
 * Captures character diffs when a broker edits AI-generated IM text.
 * Used for offline prompt calibration and LLM-as-a-judge alignment.
 * @see SDD §7 S2-T6
 */

/**
 * Payload for tracking changes made by a broker to an AI-generated section.
 */
export interface EditDiffPayload {
  /** Unique identifier of the deal context */
  dealId: string;
  /** Section key indicating which part of the IM was edited (e.g., 'executive_summary') */
  sectionKey: string;
  /** The original text generated by the AI */
  originalAiContent: string;
  /** The final text after broker's edits */
  editedBrokerContent: string;
}

export type DiffImpact = 'cosmetic' | 'material' | 'critical';

export interface VersionDiff extends EditDiffRecord {
  impact: DiffImpact;
}

/**
 * Persistent record of character diffs for prompt calibration.
 */
export interface EditDiffRecord {
  /** Deal identifier */
  deal_id: string;
  /** Section identifier */
  section_key: string;
  /** AI's original text output */
  original_ai_content: string;
  /** Broker's final text output */
  edited_broker_content: string;
  /** Absolute difference in character count between original and edited text */
  char_diff_count: number;
  /** Timestamp of the edit record creation */
  created_at: string;
}

/**
 * Computes the character difference between AI-generated content and a broker's edits.
 * Used to collect metrics for offline LLM prompt calibration.
 * 
 * @param {EditDiffPayload} payload - The payload containing original and edited texts.
 * @returns {VersionDiff} The computed record including the character diff count and impact.
 * @example
 * const diff = computeEditDiff({ dealId: 'd1', sectionKey: 'summary', originalAiContent: 'Short', editedBrokerContent: 'Longer' });
 * // diff.char_diff_count === 1
 */
export function computeEditDiff(payload: EditDiffPayload): VersionDiff {
  const origLen = payload.originalAiContent.length;
  const editLen = payload.editedBrokerContent.length;
  const charDiffCount = Math.abs(origLen - editLen);
  
  let impact: DiffImpact = 'cosmetic';
  if (charDiffCount > 50) impact = 'material';
  if (charDiffCount > 200) impact = 'critical';

  return {
    deal_id: payload.dealId,
    section_key: payload.sectionKey,
    original_ai_content: payload.originalAiContent,
    edited_broker_content: payload.editedBrokerContent,
    char_diff_count: charDiffCount,
    impact,
    created_at: new Date().toISOString(),
  };
}
