/**
 * @module EditDiffCollector
 * @description CREDEAL v3 IM Edit Diff Collector
 * 
 * Captures character diffs when a broker edits AI-generated IM text.
 * Used for offline prompt calibration and LLM-as-a-judge alignment.
 * @see SDD §7 S2-T6
 */

/**
 * Payload for tracking changes made by a broker to an AI-generated section.
 */
export interface EditDiffPayload {
  /** Unique identifier of the deal context */
  dealId: string;
  /** Section key indicating which part of the IM was edited (e.g., 'executive_summary') */
  sectionKey: string;
  /** The original text generated by the AI */
  originalAiContent: string;
  /** The final text after broker's edits */
  editedBrokerContent: string;
}

export type DiffImpact = 'cosmetic' | 'material' | 'critical';

export interface VersionDiff extends EditDiffRecord {
  impact: DiffImpact;
}

/**
 * Persistent record of character diffs for prompt calibration.
 */
export interface EditDiffRecord {
  /** Deal identifier */
  deal_id: string;
  /** Section identifier */
  section_key: string;
  /** AI's original text output */
  original_ai_content: string;
  /** Broker's final text output */
  edited_broker_content: string;
  /** Absolute difference in character count between original and edited text */
  char_diff_count: number;
  /** Timestamp of the edit record creation */
  created_at: string;
}

/**
 * Computes the character difference between AI-generated content and a broker's edits.
 * Used to collect metrics for offline LLM prompt calibration.
 * 
 * @param {EditDiffPayload} payload - The payload containing original and edited texts.
 * @returns {VersionDiff} The computed record including the character diff count and impact.
 * @example
 * const diff = computeEditDiff({ dealId: 'd1', sectionKey: 'summary', originalAiContent: 'Short', editedBrokerContent: 'Longer' });
 * // diff.char_diff_count === 1
 */
export function computeEditDiff(payload: EditDiffPayload): VersionDiff {
  const origLen = payload.originalAiContent.length;
  const editLen = payload.editedBrokerContent.length;
  const charDiffCount = Math.abs(origLen - editLen);
  
  let impact: DiffImpact = 'cosmetic';
  if (charDiffCount > 50) impact = 'material';
  if (charDiffCount > 200) impact = 'critical';

  return {
    deal_id: payload.dealId,
    section_key: payload.sectionKey,
    original_ai_content: payload.originalAiContent,
    edited_broker_content: payload.editedBrokerContent,
    char_diff_count: charDiffCount,
    impact,
    created_at: new Date().toISOString(),
  };
}

// ─── PIPE-06.1: 슬롯 기반 재발행 diff ──────────────────────────────────────

/** critical 변경으로 간주되는 슬롯 키 */
const CRITICAL_SLOTS = new Set([
  'asking_price', 'price_band_krw', 'total_area_sqm', 'plat_area_sqm',
  'pnu', 'address', 'encumbrance', 'lien', 'lease_rights',
]);

/** material 변경으로 간주되는 슬롯 키 */
const MATERIAL_SLOTS = new Set([
  'vacancy_pct', 'monthly_rent_total_krw', 'asset_type',
  'investment_posture', 'cap_rate', 'floor_leases',
]);

/** 슬롯 수준 변경 사항 */
export interface SlotChange {
  slot: string;
  before: unknown;
  after: unknown;
  impact: DiffImpact;
}

/** 버전 간 전체 변경 보고 */
export interface VersionDiffReport {
  from: number;
  to: number;
  changes: SlotChange[];
  hasCritical: boolean;
  hasMaterial: boolean;
  /** critical 변경 시 기존 Pro 권한 자동 무효화 필요 여부 */
  shouldInvalidateProAccess: boolean;
}

/**
 * 두 딜 버전의 슬롯 값을 비교하여 diff 보고서 생성
 * PIPE-06.1: critical → Pro 무효화, material → 재발행 경고
 */
export function computeSlotDiff(
  fromVersion: number,
  toVersion: number,
  beforeSlots: Record<string, unknown>,
  afterSlots: Record<string, unknown>,
): VersionDiffReport {
  const changes: SlotChange[] = [];
  const allKeys = new Set([...Object.keys(beforeSlots), ...Object.keys(afterSlots)]);

  for (const key of allKeys) {
    const before = beforeSlots[key];
    const after = afterSlots[key];
    if (JSON.stringify(before) !== JSON.stringify(after)) {
      let impact: DiffImpact = 'cosmetic';
      if (CRITICAL_SLOTS.has(key)) impact = 'critical';
      else if (MATERIAL_SLOTS.has(key)) impact = 'material';
      changes.push({ slot: key, before, after, impact });
    }
  }

  const hasCritical = changes.some(c => c.impact === 'critical');
  const hasMaterial = changes.some(c => c.impact === 'material');

  return {
    from: fromVersion,
    to: toVersion,
    changes,
    hasCritical,
    hasMaterial,
    shouldInvalidateProAccess: hasCritical,
  };
}
