/**
 * @module SubscriberProfile
 * @description Builds behavioral profiles for magazine subscribers.
 * Tracks reading patterns to auto-generate buyer intent drafts.
 * @see docs/credal_v3/SDD-magazine.md MG-B2
 */

export type SubscriberSegment = 'investor' | 'seller' | 'owner';

export interface InterestProfile {
  assetTypes: string[];
  regions: string[];
  budgetRange: { min: number; max: number };
  preferredCapRate: { min: number; max: number };
  readArticleCount: number;
  lastEngagedAt: string;
  topics?: string[];
  hobbies?: string[];
}

export interface SubscriberProfile {
  subscriberId: string;
  email: string;
  segment: SubscriberSegment;
  interestProfile: InterestProfile;
  engagementScore: number;
  autoGeneratedIntents: AutoIntent[];
}

export interface AutoIntent {
  assetType: string;
  region: string;
  budgetKrw: number;
  confidence: number;
  source: 'reading_pattern' | 'click_behavior' | 'slider_interaction';
}

/**
 * Computes an engagement score from subscriber activity.
 */
export function computeEngagementScore(profile: Partial<InterestProfile>): number {
  if (!profile || typeof profile !== 'object') return 0;
  let score = 0;
  const readCount = profile.readArticleCount || 0;
  const assetTypes = Array.isArray(profile.assetTypes) ? profile.assetTypes : [];
  const regions = Array.isArray(profile.regions) ? profile.regions : [];

  score += Math.min(readCount * 5, 50);
  score += assetTypes.length * 10;
  score += regions.length * 5;

  const daysSinceLastEngagement = profile.lastEngagedAt
    ? Math.max(0, (Date.now() - new Date(profile.lastEngagedAt).getTime()) / 86400000)
    : 999;
  if (daysSinceLastEngagement < 7) score += 30;
  else if (daysSinceLastEngagement < 30) score += 15;

  return Math.min(score, 100);
}

/**
 * Generates automatic buyer intent drafts from reading patterns.
 */
export function generateAutoIntents(profile: Partial<InterestProfile>): AutoIntent[] {
  const intents: AutoIntent[] = [];
  const assetTypes = Array.isArray(profile?.assetTypes) ? profile.assetTypes : [];
  const regions = Array.isArray(profile?.regions) ? profile.regions : [];
  const budgetRange = profile?.budgetRange || { min: 3000000000, max: 10000000000 };
  const readArticleCount = profile?.readArticleCount || 0;

  for (const assetType of assetTypes) {
    for (const region of regions.slice(0, 2)) {
      intents.push({
        assetType,
        region,
        budgetKrw: Math.round((budgetRange.min + budgetRange.max) / 2),
        confidence: readArticleCount > 5 ? 0.8 : 0.5,
        source: 'reading_pattern',
      });
    }
  }

  return intents;
}
