/**
 * @module SubscriberProfile
 * @description Builds behavioral profiles for magazine subscribers.
 * Tracks reading patterns to auto-generate buyer intent drafts.
 * @see docs/credal_v3/SDD-magazine.md MG-B2
 */

export type SubscriberSegment = 'investor' | 'seller' | 'owner';

export interface InterestProfile {
  assetTypes: string[];
  regions: string[];
  budgetRange: { min: number; max: number };
  preferredCapRate: { min: number; max: number };
  readArticleCount: number;
  lastEngagedAt: string;
  topics?: string[];
  hobbies?: string[];
}

export interface SubscriberProfile {
  subscriberId: string;
  email: string;
  segment: SubscriberSegment;
  interestProfile: InterestProfile;
  engagementScore: number;
  autoGeneratedIntents: AutoIntent[];
}

export interface AutoIntent {
  assetType: string;
  region: string;
  budgetKrw: number;
  confidence: number;
  source: 'reading_pattern' | 'click_behavior' | 'slider_interaction';
}

/**
 * Computes an engagement score from subscriber activity.
 */
export function computeEngagementScore(profile: InterestProfile): number {
  let score = 0;
  score += Math.min(profile.readArticleCount * 5, 50);
  score += profile.assetTypes.length * 10;
  score += profile.regions.length * 5;

  const daysSinceLastEngagement = profile.lastEngagedAt
    ? Math.max(0, (Date.now() - new Date(profile.lastEngagedAt).getTime()) / 86400000)
    : 999;
  if (daysSinceLastEngagement < 7) score += 30;
  else if (daysSinceLastEngagement < 30) score += 15;

  return Math.min(score, 100);
}

/**
 * Generates automatic buyer intent drafts from reading patterns.
 */
export function generateAutoIntents(profile: InterestProfile): AutoIntent[] {
  const intents: AutoIntent[] = [];

  for (const assetType of profile.assetTypes) {
    for (const region of profile.regions.slice(0, 2)) {
      intents.push({
        assetType,
        region,
        budgetKrw: Math.round((profile.budgetRange.min + profile.budgetRange.max) / 2),
        confidence: profile.readArticleCount > 5 ? 0.8 : 0.5,
        source: 'reading_pattern',
      });
    }
  }

  return intents;
}
