/**
 * GET /api/public/im-lite/[buildingId]/export?format=html&doc_id=...
 * Exports Mobile IM as printable HTML.
 * PDF generation is done client-side via window.print().
 */
import { NextRequest, NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/service';

function buildHtmlExport(doc: {
  title: string;
  sections: Array<{ title: string; markdown: string; icon?: string }>;
  broker: { displayName: string; company: string; phone: string };
  disclaimer: string;
  generatedAt: string;
}): string {
  const sectionHtml = doc.sections
    .map(
      (s) => `<section class="im-section">
  <h2>${escapeHtml(s.title)}</h2>
  <div class="section-content">${markdownToHtml(s.markdown)}</div>
</section>`
    )
    .join('\n');

  return `<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(doc.title)} — Mobile IM Lite</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700;900&display=swap" rel="stylesheet">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Noto Sans KR', sans-serif;
      background: #fff;
      color: #1a1a1a;
      font-size: 11pt;
      line-height: 1.6;
    }
    .page { max-width: 210mm; margin: 0 auto; padding: 20mm 15mm; }
    .header { border-bottom: 3px solid #c8ff00; padding-bottom: 16px; margin-bottom: 24px; }
    .header h1 { font-size: 22pt; font-weight: 900; color: #1a1a1a; margin-bottom: 4px; }
    .header .meta { color: #666; font-size: 9pt; }
    .im-section { margin-bottom: 24px; page-break-inside: avoid; }
    .im-section h2 { font-size: 13pt; font-weight: 700; color: #1a1a1a; border-left: 4px solid #c8ff00; padding-left: 10px; margin-bottom: 12px; }
    .section-content { font-size: 10pt; }
    .section-content p { margin-bottom: 8px; }
    .section-content h3 { font-size: 10pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #555; margin: 12px 0 6px; }
    .section-content table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 9pt; }
    .section-content th { text-align: left; padding: 6px 8px; border-bottom: 2px solid #1a1a1a; font-weight: 700; }
    .section-content td { padding: 5px 8px; border-bottom: 1px solid #e5e5e5; }
    .section-content strong { font-weight: 700; }
    .section-content blockquote { border-left: 3px solid #c8ff00; padding: 6px 10px; background: #fafafa; margin: 8px 0; font-size: 9pt; color: #555; }
    .section-content ul { padding-left: 16px; margin: 6px 0; }
    .section-content li { margin-bottom: 3px; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e5e5; font-size: 8pt; color: #888; }
    .broker-card { background: #f5f5f5; padding: 12px; border-radius: 8px; margin-bottom: 16px; }
    .broker-card strong { display: block; font-size: 11pt; font-weight: 700; }
    .no-print { display: block; background: #c8ff00; color: #000; font-weight: 700; padding: 12px 24px; text-align: center; cursor: pointer; border: none; font-size: 12pt; width: 100%; margin-bottom: 20px; border-radius: 8px; }
    @media print {
      @page { size: A4; margin: 15mm 10mm; }
      .no-print { display: none !important; }
      body { font-size: 10pt; margin: 0; padding: 0; }
      .page { padding: 0; max-width: none; }
      .im-section { page-break-inside: avoid; page-break-after: auto; }
      .section-content table { page-break-inside: avoid; }
      .footer { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
<div class="page">
  <button class="no-print" onclick="window.print()">🖨️ PDF로 저장 (인쇄)</button>
  <div class="header">
    <h1>${escapeHtml(doc.title)}</h1>
    <div class="meta">크리딜 Mobile IM Lite &nbsp;|&nbsp; AI 생성: ${new Date(doc.generatedAt).toLocaleDateString('ko-KR')} &nbsp;|&nbsp; 기밀 — 내부 열람용</div>
  </div>
  ${sectionHtml}
  <div class="footer">
    <div class="broker-card">
      <strong>${escapeHtml(doc.broker.displayName)}</strong>
      ${escapeHtml(doc.broker.company)} &nbsp;·&nbsp; ${escapeHtml(doc.broker.phone)}
    </div>
    <p>${escapeHtml(doc.disclaimer)}</p>
    <p style="margin-top:8px;color:#bbb;">Generated by 크리딜 Mobile IM Lite · Confidential</p>
  </div>
</div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function inlineMarkdown(text: string): string {
  return escapeHtml(text)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>');
}

function markdownToHtml(md: string): string {
  const lines = md.split('\n');
  const out: string[] = [];
  let inTable = false;
  let tableLines: string[] = [];

  const flushTable = () => {
    if (tableLines.length === 0) return;
    const rows = tableLines.filter((l) => !l.match(/^\|[\s-|]+\|$/));
    if (rows.length === 0) { inTable = false; tableLines = []; return; }
    const [header, ...body] = rows;
    const parseRow = (r: string) => r.split('|').slice(1, -1).map((c) => c.trim());
    const headers = parseRow(header);
    out.push('<table>');
    out.push('<thead><tr>' + headers.map((h) => `<th>${inlineMarkdown(h)}</th>`).join('') + '</tr></thead>');
    out.push('<tbody>');
    body.forEach((row) => {
      out.push('<tr>' + parseRow(row).map((c) => `<td>${inlineMarkdown(c)}</td>`).join('') + '</tr>');
    });
    out.push('</tbody></table>');
    inTable = false; tableLines = [];
  };

  for (const line of lines) {
    if (line.startsWith('|')) { inTable = true; tableLines.push(line); continue; }
    if (inTable) flushTable();
    if (line.startsWith('### ')) { out.push(`<h3>${escapeHtml(line.slice(4))}</h3>`); }
    else if (line.startsWith('## ')) { out.push(`<h2>${escapeHtml(line.slice(3))}</h2>`); }
    else if (line.startsWith('> ')) { out.push(`<blockquote>${inlineMarkdown(line.slice(2))}</blockquote>`); }
    else if (line.startsWith('- ') || line.startsWith('* ')) { out.push(`<li>${inlineMarkdown(line.slice(2))}</li>`); }
    else if (line.trim() === '') { out.push('<br>'); }
    else { out.push(`<p>${inlineMarkdown(line)}</p>`); }
  }
  if (inTable) flushTable();
  return out.join('\n');
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ buildingId: string }> }
) {
  const { buildingId } = await params;
  const { searchParams } = new URL(req.url);
  const docId = searchParams.get('doc_id');

  if (!docId) {
    return NextResponse.json({ error: 'doc_id is required' }, { status: 400 });
  }

  const supabase = createServiceClient();
  const { data: doc, error } = await supabase
    .from('document_objects')
    .select('id, title, body, created_at')
    .eq('id', docId)
    .eq('building_id', buildingId)
    .maybeSingle();

  if (error || !doc) {
    return NextResponse.json({ error: 'Document not found' }, { status: 404 });
  }

  const content = doc.body as Record<string, unknown>;
  const sections = (content?.sections ?? []) as Array<{ title: string; markdown: string }>;

  const html = buildHtmlExport({
    title: doc.title ?? 'Mobile IM Lite',
    sections,
    broker: { displayName: '담당 중개인', company: '', phone: '' },
    disclaimer: '이 문서는 AI가 생성한 참고용 자료입니다. 실제 투자 결정 전 전문가 자문을 받으시기 바랍니다.',
    generatedAt: (content?.generated_at as string) ?? doc.created_at,
  });

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'no-store',
    },
  });
}
